/*
 * Mist API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 * Contact: api@mist.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// ListSecretsResponse struct for ListSecretsResponse
type ListSecretsResponse struct {
	Data *[]Secret `json:"data,omitempty"`
	Meta *ResponseMetadata `json:"meta,omitempty"`
}

// NewListSecretsResponse instantiates a new ListSecretsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSecretsResponse() *ListSecretsResponse {
	this := ListSecretsResponse{}
	return &this
}

// NewListSecretsResponseWithDefaults instantiates a new ListSecretsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSecretsResponseWithDefaults() *ListSecretsResponse {
	this := ListSecretsResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *ListSecretsResponse) GetData() []Secret {
	if o == nil || o.Data == nil {
		var ret []Secret
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSecretsResponse) GetDataOk() (*[]Secret, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *ListSecretsResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []Secret and assigns it to the Data field.
func (o *ListSecretsResponse) SetData(v []Secret) {
	o.Data = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *ListSecretsResponse) GetMeta() ResponseMetadata {
	if o == nil || o.Meta == nil {
		var ret ResponseMetadata
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListSecretsResponse) GetMetaOk() (*ResponseMetadata, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *ListSecretsResponse) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ResponseMetadata and assigns it to the Meta field.
func (o *ListSecretsResponse) SetMeta(v ResponseMetadata) {
	o.Meta = &v
}

func (o ListSecretsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableListSecretsResponse struct {
	value *ListSecretsResponse
	isSet bool
}

func (v NullableListSecretsResponse) Get() *ListSecretsResponse {
	return v.value
}

func (v *NullableListSecretsResponse) Set(val *ListSecretsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListSecretsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListSecretsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSecretsResponse(val *ListSecretsResponse) *NullableListSecretsResponse {
	return &NullableListSecretsResponse{value: val, isSet: true}
}

func (v NullableListSecretsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSecretsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


