/*
Mist API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: api@mist.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// EditMachineRequest struct for EditMachineRequest
type EditMachineRequest struct {
	Expiration *EditMachineRequestExpiration `json:"expiration,omitempty"`
}

// NewEditMachineRequest instantiates a new EditMachineRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEditMachineRequest() *EditMachineRequest {
	this := EditMachineRequest{}
	return &this
}

// NewEditMachineRequestWithDefaults instantiates a new EditMachineRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEditMachineRequestWithDefaults() *EditMachineRequest {
	this := EditMachineRequest{}
	return &this
}

// GetExpiration returns the Expiration field value if set, zero value otherwise.
func (o *EditMachineRequest) GetExpiration() EditMachineRequestExpiration {
	if o == nil || o.Expiration == nil {
		var ret EditMachineRequestExpiration
		return ret
	}
	return *o.Expiration
}

// GetExpirationOk returns a tuple with the Expiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EditMachineRequest) GetExpirationOk() (*EditMachineRequestExpiration, bool) {
	if o == nil || o.Expiration == nil {
		return nil, false
	}
	return o.Expiration, true
}

// HasExpiration returns a boolean if a field has been set.
func (o *EditMachineRequest) HasExpiration() bool {
	if o != nil && o.Expiration != nil {
		return true
	}

	return false
}

// SetExpiration gets a reference to the given EditMachineRequestExpiration and assigns it to the Expiration field.
func (o *EditMachineRequest) SetExpiration(v EditMachineRequestExpiration) {
	o.Expiration = &v
}

func (o EditMachineRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Expiration != nil {
		toSerialize["expiration"] = o.Expiration
	}
	return json.Marshal(toSerialize)
}

type NullableEditMachineRequest struct {
	value *EditMachineRequest
	isSet bool
}

func (v NullableEditMachineRequest) Get() *EditMachineRequest {
	return v.value
}

func (v *NullableEditMachineRequest) Set(val *EditMachineRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEditMachineRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEditMachineRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditMachineRequest(val *EditMachineRequest) *NullableEditMachineRequest {
	return &NullableEditMachineRequest{value: val, isSet: true}
}

func (v NullableEditMachineRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditMachineRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


