/*
 * Mist API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 * Contact: api@mist.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// DestroyClusterResponse struct for DestroyClusterResponse
type DestroyClusterResponse struct {
	JobId *string `json:"jobId,omitempty"`
	Cloud *string `json:"cloud,omitempty"`
	Cluster *string `json:"cluster,omitempty"`
}

// NewDestroyClusterResponse instantiates a new DestroyClusterResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDestroyClusterResponse() *DestroyClusterResponse {
	this := DestroyClusterResponse{}
	return &this
}

// NewDestroyClusterResponseWithDefaults instantiates a new DestroyClusterResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDestroyClusterResponseWithDefaults() *DestroyClusterResponse {
	this := DestroyClusterResponse{}
	return &this
}

// GetJobId returns the JobId field value if set, zero value otherwise.
func (o *DestroyClusterResponse) GetJobId() string {
	if o == nil || o.JobId == nil {
		var ret string
		return ret
	}
	return *o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestroyClusterResponse) GetJobIdOk() (*string, bool) {
	if o == nil || o.JobId == nil {
		return nil, false
	}
	return o.JobId, true
}

// HasJobId returns a boolean if a field has been set.
func (o *DestroyClusterResponse) HasJobId() bool {
	if o != nil && o.JobId != nil {
		return true
	}

	return false
}

// SetJobId gets a reference to the given string and assigns it to the JobId field.
func (o *DestroyClusterResponse) SetJobId(v string) {
	o.JobId = &v
}

// GetCloud returns the Cloud field value if set, zero value otherwise.
func (o *DestroyClusterResponse) GetCloud() string {
	if o == nil || o.Cloud == nil {
		var ret string
		return ret
	}
	return *o.Cloud
}

// GetCloudOk returns a tuple with the Cloud field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestroyClusterResponse) GetCloudOk() (*string, bool) {
	if o == nil || o.Cloud == nil {
		return nil, false
	}
	return o.Cloud, true
}

// HasCloud returns a boolean if a field has been set.
func (o *DestroyClusterResponse) HasCloud() bool {
	if o != nil && o.Cloud != nil {
		return true
	}

	return false
}

// SetCloud gets a reference to the given string and assigns it to the Cloud field.
func (o *DestroyClusterResponse) SetCloud(v string) {
	o.Cloud = &v
}

// GetCluster returns the Cluster field value if set, zero value otherwise.
func (o *DestroyClusterResponse) GetCluster() string {
	if o == nil || o.Cluster == nil {
		var ret string
		return ret
	}
	return *o.Cluster
}

// GetClusterOk returns a tuple with the Cluster field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DestroyClusterResponse) GetClusterOk() (*string, bool) {
	if o == nil || o.Cluster == nil {
		return nil, false
	}
	return o.Cluster, true
}

// HasCluster returns a boolean if a field has been set.
func (o *DestroyClusterResponse) HasCluster() bool {
	if o != nil && o.Cluster != nil {
		return true
	}

	return false
}

// SetCluster gets a reference to the given string and assigns it to the Cluster field.
func (o *DestroyClusterResponse) SetCluster(v string) {
	o.Cluster = &v
}

func (o DestroyClusterResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.JobId != nil {
		toSerialize["jobId"] = o.JobId
	}
	if o.Cloud != nil {
		toSerialize["cloud"] = o.Cloud
	}
	if o.Cluster != nil {
		toSerialize["cluster"] = o.Cluster
	}
	return json.Marshal(toSerialize)
}

type NullableDestroyClusterResponse struct {
	value *DestroyClusterResponse
	isSet bool
}

func (v NullableDestroyClusterResponse) Get() *DestroyClusterResponse {
	return v.value
}

func (v *NullableDestroyClusterResponse) Set(val *DestroyClusterResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDestroyClusterResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDestroyClusterResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDestroyClusterResponse(val *DestroyClusterResponse) *NullableDestroyClusterResponse {
	return &NullableDestroyClusterResponse{value: val, isSet: true}
}

func (v NullableDestroyClusterResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDestroyClusterResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


