/*
 * Mist API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 * Contact: api@mist.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// AlibabaSubnetRequest struct for AlibabaSubnetRequest
type AlibabaSubnetRequest struct {
	Provider string `json:"provider"`
	AvailabilityZone string `json:"availability_zone"`
}

// NewAlibabaSubnetRequest instantiates a new AlibabaSubnetRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlibabaSubnetRequest(provider string, availabilityZone string, ) *AlibabaSubnetRequest {
	this := AlibabaSubnetRequest{}
	this.Provider = provider
	this.AvailabilityZone = availabilityZone
	return &this
}

// NewAlibabaSubnetRequestWithDefaults instantiates a new AlibabaSubnetRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlibabaSubnetRequestWithDefaults() *AlibabaSubnetRequest {
	this := AlibabaSubnetRequest{}
	return &this
}

// GetProvider returns the Provider field value
func (o *AlibabaSubnetRequest) GetProvider() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *AlibabaSubnetRequest) GetProviderOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *AlibabaSubnetRequest) SetProvider(v string) {
	o.Provider = v
}

// GetAvailabilityZone returns the AvailabilityZone field value
func (o *AlibabaSubnetRequest) GetAvailabilityZone() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.AvailabilityZone
}

// GetAvailabilityZoneOk returns a tuple with the AvailabilityZone field value
// and a boolean to check if the value has been set.
func (o *AlibabaSubnetRequest) GetAvailabilityZoneOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AvailabilityZone, true
}

// SetAvailabilityZone sets field value
func (o *AlibabaSubnetRequest) SetAvailabilityZone(v string) {
	o.AvailabilityZone = v
}

func (o AlibabaSubnetRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["provider"] = o.Provider
	}
	if true {
		toSerialize["availability_zone"] = o.AvailabilityZone
	}
	return json.Marshal(toSerialize)
}

type NullableAlibabaSubnetRequest struct {
	value *AlibabaSubnetRequest
	isSet bool
}

func (v NullableAlibabaSubnetRequest) Get() *AlibabaSubnetRequest {
	return v.value
}

func (v *NullableAlibabaSubnetRequest) Set(val *AlibabaSubnetRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAlibabaSubnetRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAlibabaSubnetRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlibabaSubnetRequest(val *AlibabaSubnetRequest) *NullableAlibabaSubnetRequest {
	return &NullableAlibabaSubnetRequest{value: val, isSet: true}
}

func (v NullableAlibabaSubnetRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlibabaSubnetRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


