/*
 * Mist API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 * Contact: api@mist.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// EquinixCloudRequest struct for EquinixCloudRequest
type EquinixCloudRequest struct {
	Provider string `json:"provider"`
	Credentials EquinixCredentials `json:"credentials"`
	Features *CloudFeatures `json:"features,omitempty"`
}

// NewEquinixCloudRequest instantiates a new EquinixCloudRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEquinixCloudRequest(provider string, credentials EquinixCredentials, ) *EquinixCloudRequest {
	this := EquinixCloudRequest{}
	this.Provider = provider
	this.Credentials = credentials
	return &this
}

// NewEquinixCloudRequestWithDefaults instantiates a new EquinixCloudRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEquinixCloudRequestWithDefaults() *EquinixCloudRequest {
	this := EquinixCloudRequest{}
	return &this
}

// GetProvider returns the Provider field value
func (o *EquinixCloudRequest) GetProvider() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *EquinixCloudRequest) GetProviderOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *EquinixCloudRequest) SetProvider(v string) {
	o.Provider = v
}

// GetCredentials returns the Credentials field value
func (o *EquinixCloudRequest) GetCredentials() EquinixCredentials {
	if o == nil  {
		var ret EquinixCredentials
		return ret
	}

	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value
// and a boolean to check if the value has been set.
func (o *EquinixCloudRequest) GetCredentialsOk() (*EquinixCredentials, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Credentials, true
}

// SetCredentials sets field value
func (o *EquinixCloudRequest) SetCredentials(v EquinixCredentials) {
	o.Credentials = v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *EquinixCloudRequest) GetFeatures() CloudFeatures {
	if o == nil || o.Features == nil {
		var ret CloudFeatures
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EquinixCloudRequest) GetFeaturesOk() (*CloudFeatures, bool) {
	if o == nil || o.Features == nil {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *EquinixCloudRequest) HasFeatures() bool {
	if o != nil && o.Features != nil {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given CloudFeatures and assigns it to the Features field.
func (o *EquinixCloudRequest) SetFeatures(v CloudFeatures) {
	o.Features = &v
}

func (o EquinixCloudRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["provider"] = o.Provider
	}
	if true {
		toSerialize["credentials"] = o.Credentials
	}
	if o.Features != nil {
		toSerialize["features"] = o.Features
	}
	return json.Marshal(toSerialize)
}

type NullableEquinixCloudRequest struct {
	value *EquinixCloudRequest
	isSet bool
}

func (v NullableEquinixCloudRequest) Get() *EquinixCloudRequest {
	return v.value
}

func (v *NullableEquinixCloudRequest) Set(val *EquinixCloudRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEquinixCloudRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEquinixCloudRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEquinixCloudRequest(val *EquinixCloudRequest) *NullableEquinixCloudRequest {
	return &NullableEquinixCloudRequest{value: val, isSet: true}
}

func (v NullableEquinixCloudRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEquinixCloudRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


