/*
Mist API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: api@mist.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// OpenstackCloudRequest struct for OpenstackCloudRequest
type OpenstackCloudRequest struct {
	Provider string `json:"provider"`
	Credentials OpenstackCredentials `json:"credentials"`
	Features *CloudFeatures `json:"features,omitempty"`
}

// NewOpenstackCloudRequest instantiates a new OpenstackCloudRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOpenstackCloudRequest(provider string, credentials OpenstackCredentials) *OpenstackCloudRequest {
	this := OpenstackCloudRequest{}
	this.Provider = provider
	this.Credentials = credentials
	return &this
}

// NewOpenstackCloudRequestWithDefaults instantiates a new OpenstackCloudRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOpenstackCloudRequestWithDefaults() *OpenstackCloudRequest {
	this := OpenstackCloudRequest{}
	return &this
}

// GetProvider returns the Provider field value
func (o *OpenstackCloudRequest) GetProvider() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *OpenstackCloudRequest) GetProviderOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *OpenstackCloudRequest) SetProvider(v string) {
	o.Provider = v
}

// GetCredentials returns the Credentials field value
func (o *OpenstackCloudRequest) GetCredentials() OpenstackCredentials {
	if o == nil {
		var ret OpenstackCredentials
		return ret
	}

	return o.Credentials
}

// GetCredentialsOk returns a tuple with the Credentials field value
// and a boolean to check if the value has been set.
func (o *OpenstackCloudRequest) GetCredentialsOk() (*OpenstackCredentials, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Credentials, true
}

// SetCredentials sets field value
func (o *OpenstackCloudRequest) SetCredentials(v OpenstackCredentials) {
	o.Credentials = v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *OpenstackCloudRequest) GetFeatures() CloudFeatures {
	if o == nil || o.Features == nil {
		var ret CloudFeatures
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OpenstackCloudRequest) GetFeaturesOk() (*CloudFeatures, bool) {
	if o == nil || o.Features == nil {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *OpenstackCloudRequest) HasFeatures() bool {
	if o != nil && o.Features != nil {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given CloudFeatures and assigns it to the Features field.
func (o *OpenstackCloudRequest) SetFeatures(v CloudFeatures) {
	o.Features = &v
}

func (o OpenstackCloudRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["provider"] = o.Provider
	}
	if true {
		toSerialize["credentials"] = o.Credentials
	}
	if o.Features != nil {
		toSerialize["features"] = o.Features
	}
	return json.Marshal(toSerialize)
}

type NullableOpenstackCloudRequest struct {
	value *OpenstackCloudRequest
	isSet bool
}

func (v NullableOpenstackCloudRequest) Get() *OpenstackCloudRequest {
	return v.value
}

func (v *NullableOpenstackCloudRequest) Set(val *OpenstackCloudRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableOpenstackCloudRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableOpenstackCloudRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOpenstackCloudRequest(val *OpenstackCloudRequest) *NullableOpenstackCloudRequest {
	return &NullableOpenstackCloudRequest{value: val, isSet: true}
}

func (v NullableOpenstackCloudRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOpenstackCloudRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


