/*
 * Mist API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 * Contact: api@mist.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// AmazonClusterRequest struct for AmazonClusterRequest
type AmazonClusterRequest struct {
	Provider string `json:"provider"`
	// The Amazon Resource Name (ARN) of the IAM role that provides permissions for the Kubernetes control plane to make calls to AWS API operations on your behalf
	RoleArn string `json:"role_arn"`
	// The security groups associated with the cross-account elastic network interfaces that are used to allow communication between your nodes and the Kubernetes control plane
	SecurityGroupIds []string `json:"security_group_ids"`
	// The subnets associated with the cluster
	SubnetIds []string `json:"subnet_ids"`
	// The VPC associated with the cluster
	VpcId string `json:"vpc_id"`
}

// NewAmazonClusterRequest instantiates a new AmazonClusterRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAmazonClusterRequest(provider string, roleArn string, securityGroupIds []string, subnetIds []string, vpcId string, ) *AmazonClusterRequest {
	this := AmazonClusterRequest{}
	this.Provider = provider
	this.RoleArn = roleArn
	this.SecurityGroupIds = securityGroupIds
	this.SubnetIds = subnetIds
	this.VpcId = vpcId
	return &this
}

// NewAmazonClusterRequestWithDefaults instantiates a new AmazonClusterRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAmazonClusterRequestWithDefaults() *AmazonClusterRequest {
	this := AmazonClusterRequest{}
	return &this
}

// GetProvider returns the Provider field value
func (o *AmazonClusterRequest) GetProvider() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Provider
}

// GetProviderOk returns a tuple with the Provider field value
// and a boolean to check if the value has been set.
func (o *AmazonClusterRequest) GetProviderOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Provider, true
}

// SetProvider sets field value
func (o *AmazonClusterRequest) SetProvider(v string) {
	o.Provider = v
}

// GetRoleArn returns the RoleArn field value
func (o *AmazonClusterRequest) GetRoleArn() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value
// and a boolean to check if the value has been set.
func (o *AmazonClusterRequest) GetRoleArnOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RoleArn, true
}

// SetRoleArn sets field value
func (o *AmazonClusterRequest) SetRoleArn(v string) {
	o.RoleArn = v
}

// GetSecurityGroupIds returns the SecurityGroupIds field value
func (o *AmazonClusterRequest) GetSecurityGroupIds() []string {
	if o == nil  {
		var ret []string
		return ret
	}

	return o.SecurityGroupIds
}

// GetSecurityGroupIdsOk returns a tuple with the SecurityGroupIds field value
// and a boolean to check if the value has been set.
func (o *AmazonClusterRequest) GetSecurityGroupIdsOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SecurityGroupIds, true
}

// SetSecurityGroupIds sets field value
func (o *AmazonClusterRequest) SetSecurityGroupIds(v []string) {
	o.SecurityGroupIds = v
}

// GetSubnetIds returns the SubnetIds field value
func (o *AmazonClusterRequest) GetSubnetIds() []string {
	if o == nil  {
		var ret []string
		return ret
	}

	return o.SubnetIds
}

// GetSubnetIdsOk returns a tuple with the SubnetIds field value
// and a boolean to check if the value has been set.
func (o *AmazonClusterRequest) GetSubnetIdsOk() (*[]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SubnetIds, true
}

// SetSubnetIds sets field value
func (o *AmazonClusterRequest) SetSubnetIds(v []string) {
	o.SubnetIds = v
}

// GetVpcId returns the VpcId field value
func (o *AmazonClusterRequest) GetVpcId() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.VpcId
}

// GetVpcIdOk returns a tuple with the VpcId field value
// and a boolean to check if the value has been set.
func (o *AmazonClusterRequest) GetVpcIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.VpcId, true
}

// SetVpcId sets field value
func (o *AmazonClusterRequest) SetVpcId(v string) {
	o.VpcId = v
}

func (o AmazonClusterRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["provider"] = o.Provider
	}
	if true {
		toSerialize["role_arn"] = o.RoleArn
	}
	if true {
		toSerialize["security_group_ids"] = o.SecurityGroupIds
	}
	if true {
		toSerialize["subnet_ids"] = o.SubnetIds
	}
	if true {
		toSerialize["vpc_id"] = o.VpcId
	}
	return json.Marshal(toSerialize)
}

type NullableAmazonClusterRequest struct {
	value *AmazonClusterRequest
	isSet bool
}

func (v NullableAmazonClusterRequest) Get() *AmazonClusterRequest {
	return v.value
}

func (v *NullableAmazonClusterRequest) Set(val *AmazonClusterRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAmazonClusterRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAmazonClusterRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAmazonClusterRequest(val *AmazonClusterRequest) *NullableAmazonClusterRequest {
	return &NullableAmazonClusterRequest{value: val, isSet: true}
}

func (v NullableAmazonClusterRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAmazonClusterRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


