/*
Mist API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: api@mist.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// OrgResourcesSummaryKeys struct for OrgResourcesSummaryKeys
type OrgResourcesSummaryKeys struct {
	Total *int32 `json:"total,omitempty"`
}

// NewOrgResourcesSummaryKeys instantiates a new OrgResourcesSummaryKeys object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrgResourcesSummaryKeys() *OrgResourcesSummaryKeys {
	this := OrgResourcesSummaryKeys{}
	return &this
}

// NewOrgResourcesSummaryKeysWithDefaults instantiates a new OrgResourcesSummaryKeys object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrgResourcesSummaryKeysWithDefaults() *OrgResourcesSummaryKeys {
	this := OrgResourcesSummaryKeys{}
	return &this
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *OrgResourcesSummaryKeys) GetTotal() int32 {
	if o == nil || o.Total == nil {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrgResourcesSummaryKeys) GetTotalOk() (*int32, bool) {
	if o == nil || o.Total == nil {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *OrgResourcesSummaryKeys) HasTotal() bool {
	if o != nil && o.Total != nil {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *OrgResourcesSummaryKeys) SetTotal(v int32) {
	o.Total = &v
}

func (o OrgResourcesSummaryKeys) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Total != nil {
		toSerialize["total"] = o.Total
	}
	return json.Marshal(toSerialize)
}

type NullableOrgResourcesSummaryKeys struct {
	value *OrgResourcesSummaryKeys
	isSet bool
}

func (v NullableOrgResourcesSummaryKeys) Get() *OrgResourcesSummaryKeys {
	return v.value
}

func (v *NullableOrgResourcesSummaryKeys) Set(val *OrgResourcesSummaryKeys) {
	v.value = val
	v.isSet = true
}

func (v NullableOrgResourcesSummaryKeys) IsSet() bool {
	return v.isSet
}

func (v *NullableOrgResourcesSummaryKeys) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrgResourcesSummaryKeys(val *OrgResourcesSummaryKeys) *NullableOrgResourcesSummaryKeys {
	return &NullableOrgResourcesSummaryKeys{value: val, isSet: true}
}

func (v NullableOrgResourcesSummaryKeys) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrgResourcesSummaryKeys) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


