/*
 * Mist API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 * Contact: api@mist.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// InlineScript struct for InlineScript
type InlineScript struct {
	Inline string `json:"inline"`
}

// NewInlineScript instantiates a new InlineScript object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineScript(inline string, ) *InlineScript {
	this := InlineScript{}
	this.Inline = inline
	return &this
}

// NewInlineScriptWithDefaults instantiates a new InlineScript object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineScriptWithDefaults() *InlineScript {
	this := InlineScript{}
	return &this
}

// GetInline returns the Inline field value
func (o *InlineScript) GetInline() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Inline
}

// GetInlineOk returns a tuple with the Inline field value
// and a boolean to check if the value has been set.
func (o *InlineScript) GetInlineOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Inline, true
}

// SetInline sets field value
func (o *InlineScript) SetInline(v string) {
	o.Inline = v
}

func (o InlineScript) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["inline"] = o.Inline
	}
	return json.Marshal(toSerialize)
}

type NullableInlineScript struct {
	value *InlineScript
	isSet bool
}

func (v NullableInlineScript) Get() *InlineScript {
	return v.value
}

func (v *NullableInlineScript) Set(val *InlineScript) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineScript) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineScript) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineScript(val *InlineScript) *NullableInlineScript {
	return &NullableInlineScript{value: val, isSet: true}
}

func (v NullableInlineScript) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineScript) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


