/*
 * Mist API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 2.0.0
 * Contact: api@mist.io
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
	"fmt"
)

// EditCloudRequest struct for EditCloudRequest
type EditCloudRequest struct {
	EditCloudRequestAnyOf *EditCloudRequestAnyOf
	map[string]interface{} *map[string]interface{}
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *EditCloudRequest) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into EditCloudRequestAnyOf
	err = json.Unmarshal(data, &dst.EditCloudRequestAnyOf);
	if err == nil {
		jsonEditCloudRequestAnyOf, _ := json.Marshal(dst.EditCloudRequestAnyOf)
		if string(jsonEditCloudRequestAnyOf) == "{}" { // empty struct
			dst.EditCloudRequestAnyOf = nil
		} else {
			return nil // data stored in dst.EditCloudRequestAnyOf, return on the first match
		}
	} else {
		dst.EditCloudRequestAnyOf = nil
	}

	// try to unmarshal JSON data into map[string]interface{}
	err = json.Unmarshal(data, &dst.map[string]interface{});
	if err == nil {
		jsonmap[string]interface{}, _ := json.Marshal(dst.map[string]interface{})
		if string(jsonmap[string]interface{}) == "{}" { // empty struct
			dst.map[string]interface{} = nil
		} else {
			return nil // data stored in dst.map[string]interface{}, return on the first match
		}
	} else {
		dst.map[string]interface{} = nil
	}

	return fmt.Errorf("Data failed to match schemas in anyOf(EditCloudRequest)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src *EditCloudRequest) MarshalJSON() ([]byte, error) {
	if src.EditCloudRequestAnyOf != nil {
		return json.Marshal(&src.EditCloudRequestAnyOf)
	}

	if src.map[string]interface{} != nil {
		return json.Marshal(&src.map[string]interface{})
	}

	return nil, nil // no data in anyOf schemas
}

type NullableEditCloudRequest struct {
	value *EditCloudRequest
	isSet bool
}

func (v NullableEditCloudRequest) Get() *EditCloudRequest {
	return v.value
}

func (v *NullableEditCloudRequest) Set(val *EditCloudRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEditCloudRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEditCloudRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEditCloudRequest(val *EditCloudRequest) *NullableEditCloudRequest {
	return &NullableEditCloudRequest{value: val, isSet: true}
}

func (v NullableEditCloudRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEditCloudRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


