/*
Mist API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: api@mist.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// GoogleCloudFeatures struct for GoogleCloudFeatures
type GoogleCloudFeatures struct {
	Compute *bool `json:"compute,omitempty"`
	Dns *bool `json:"dns,omitempty"`
	Container *bool `json:"container,omitempty"`
	Objectstorage *bool `json:"objectstorage,omitempty"`
}

// NewGoogleCloudFeatures instantiates a new GoogleCloudFeatures object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGoogleCloudFeatures() *GoogleCloudFeatures {
	this := GoogleCloudFeatures{}
	var compute bool = true
	this.Compute = &compute
	var dns bool = false
	this.Dns = &dns
	var container bool = false
	this.Container = &container
	return &this
}

// NewGoogleCloudFeaturesWithDefaults instantiates a new GoogleCloudFeatures object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGoogleCloudFeaturesWithDefaults() *GoogleCloudFeatures {
	this := GoogleCloudFeatures{}
	var compute bool = true
	this.Compute = &compute
	var dns bool = false
	this.Dns = &dns
	var container bool = false
	this.Container = &container
	return &this
}

// GetCompute returns the Compute field value if set, zero value otherwise.
func (o *GoogleCloudFeatures) GetCompute() bool {
	if o == nil || o.Compute == nil {
		var ret bool
		return ret
	}
	return *o.Compute
}

// GetComputeOk returns a tuple with the Compute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleCloudFeatures) GetComputeOk() (*bool, bool) {
	if o == nil || o.Compute == nil {
		return nil, false
	}
	return o.Compute, true
}

// HasCompute returns a boolean if a field has been set.
func (o *GoogleCloudFeatures) HasCompute() bool {
	if o != nil && o.Compute != nil {
		return true
	}

	return false
}

// SetCompute gets a reference to the given bool and assigns it to the Compute field.
func (o *GoogleCloudFeatures) SetCompute(v bool) {
	o.Compute = &v
}

// GetDns returns the Dns field value if set, zero value otherwise.
func (o *GoogleCloudFeatures) GetDns() bool {
	if o == nil || o.Dns == nil {
		var ret bool
		return ret
	}
	return *o.Dns
}

// GetDnsOk returns a tuple with the Dns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleCloudFeatures) GetDnsOk() (*bool, bool) {
	if o == nil || o.Dns == nil {
		return nil, false
	}
	return o.Dns, true
}

// HasDns returns a boolean if a field has been set.
func (o *GoogleCloudFeatures) HasDns() bool {
	if o != nil && o.Dns != nil {
		return true
	}

	return false
}

// SetDns gets a reference to the given bool and assigns it to the Dns field.
func (o *GoogleCloudFeatures) SetDns(v bool) {
	o.Dns = &v
}

// GetContainer returns the Container field value if set, zero value otherwise.
func (o *GoogleCloudFeatures) GetContainer() bool {
	if o == nil || o.Container == nil {
		var ret bool
		return ret
	}
	return *o.Container
}

// GetContainerOk returns a tuple with the Container field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleCloudFeatures) GetContainerOk() (*bool, bool) {
	if o == nil || o.Container == nil {
		return nil, false
	}
	return o.Container, true
}

// HasContainer returns a boolean if a field has been set.
func (o *GoogleCloudFeatures) HasContainer() bool {
	if o != nil && o.Container != nil {
		return true
	}

	return false
}

// SetContainer gets a reference to the given bool and assigns it to the Container field.
func (o *GoogleCloudFeatures) SetContainer(v bool) {
	o.Container = &v
}

// GetObjectstorage returns the Objectstorage field value if set, zero value otherwise.
func (o *GoogleCloudFeatures) GetObjectstorage() bool {
	if o == nil || o.Objectstorage == nil {
		var ret bool
		return ret
	}
	return *o.Objectstorage
}

// GetObjectstorageOk returns a tuple with the Objectstorage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GoogleCloudFeatures) GetObjectstorageOk() (*bool, bool) {
	if o == nil || o.Objectstorage == nil {
		return nil, false
	}
	return o.Objectstorage, true
}

// HasObjectstorage returns a boolean if a field has been set.
func (o *GoogleCloudFeatures) HasObjectstorage() bool {
	if o != nil && o.Objectstorage != nil {
		return true
	}

	return false
}

// SetObjectstorage gets a reference to the given bool and assigns it to the Objectstorage field.
func (o *GoogleCloudFeatures) SetObjectstorage(v bool) {
	o.Objectstorage = &v
}

func (o GoogleCloudFeatures) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Compute != nil {
		toSerialize["compute"] = o.Compute
	}
	if o.Dns != nil {
		toSerialize["dns"] = o.Dns
	}
	if o.Container != nil {
		toSerialize["container"] = o.Container
	}
	if o.Objectstorage != nil {
		toSerialize["objectstorage"] = o.Objectstorage
	}
	return json.Marshal(toSerialize)
}

type NullableGoogleCloudFeatures struct {
	value *GoogleCloudFeatures
	isSet bool
}

func (v NullableGoogleCloudFeatures) Get() *GoogleCloudFeatures {
	return v.value
}

func (v *NullableGoogleCloudFeatures) Set(val *GoogleCloudFeatures) {
	v.value = val
	v.isSet = true
}

func (v NullableGoogleCloudFeatures) IsSet() bool {
	return v.isSet
}

func (v *NullableGoogleCloudFeatures) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGoogleCloudFeatures(val *GoogleCloudFeatures) *NullableGoogleCloudFeatures {
	return &NullableGoogleCloudFeatures{value: val, isSet: true}
}

func (v NullableGoogleCloudFeatures) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGoogleCloudFeatures) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


