/*
Mist API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: api@mist.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// ScriptToRunAllOf struct for ScriptToRunAllOf
type ScriptToRunAllOf struct {
	// the script's type: inline, existing 
	Type string `json:"type"`
}

// NewScriptToRunAllOf instantiates a new ScriptToRunAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewScriptToRunAllOf(type_ string) *ScriptToRunAllOf {
	this := ScriptToRunAllOf{}
	this.Type = type_
	return &this
}

// NewScriptToRunAllOfWithDefaults instantiates a new ScriptToRunAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewScriptToRunAllOfWithDefaults() *ScriptToRunAllOf {
	this := ScriptToRunAllOf{}
	return &this
}

// GetType returns the Type field value
func (o *ScriptToRunAllOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ScriptToRunAllOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ScriptToRunAllOf) SetType(v string) {
	o.Type = v
}

func (o ScriptToRunAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableScriptToRunAllOf struct {
	value *ScriptToRunAllOf
	isSet bool
}

func (v NullableScriptToRunAllOf) Get() *ScriptToRunAllOf {
	return v.value
}

func (v *NullableScriptToRunAllOf) Set(val *ScriptToRunAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableScriptToRunAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableScriptToRunAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableScriptToRunAllOf(val *ScriptToRunAllOf) *NullableScriptToRunAllOf {
	return &NullableScriptToRunAllOf{value: val, isSet: true}
}

func (v NullableScriptToRunAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableScriptToRunAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


