/*
Mist API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: api@mist.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// RackspaceCredentials struct for RackspaceCredentials
type RackspaceCredentials struct {
	Provider *string `json:"provider,omitempty"`
	// Your Rackspace Cloud username
	Username string `json:"username"`
	// Your Rackspace Cloud API key
	Apikey string `json:"apikey"`
	// Your Rackspace Cloud region
	Region string `json:"region"`
}

// NewRackspaceCredentials instantiates a new RackspaceCredentials object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRackspaceCredentials(username string, apikey string, region string) *RackspaceCredentials {
	this := RackspaceCredentials{}
	this.Username = username
	this.Apikey = apikey
	this.Region = region
	return &this
}

// NewRackspaceCredentialsWithDefaults instantiates a new RackspaceCredentials object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRackspaceCredentialsWithDefaults() *RackspaceCredentials {
	this := RackspaceCredentials{}
	return &this
}

// GetProvider returns the Provider field value if set, zero value otherwise.
func (o *RackspaceCredentials) GetProvider() string {
	if o == nil || o.Provider == nil {
		var ret string
		return ret
	}
	return *o.Provider
}

// GetProviderOk returns a tuple with the Provider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RackspaceCredentials) GetProviderOk() (*string, bool) {
	if o == nil || o.Provider == nil {
		return nil, false
	}
	return o.Provider, true
}

// HasProvider returns a boolean if a field has been set.
func (o *RackspaceCredentials) HasProvider() bool {
	if o != nil && o.Provider != nil {
		return true
	}

	return false
}

// SetProvider gets a reference to the given string and assigns it to the Provider field.
func (o *RackspaceCredentials) SetProvider(v string) {
	o.Provider = &v
}

// GetUsername returns the Username field value
func (o *RackspaceCredentials) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *RackspaceCredentials) GetUsernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *RackspaceCredentials) SetUsername(v string) {
	o.Username = v
}

// GetApikey returns the Apikey field value
func (o *RackspaceCredentials) GetApikey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Apikey
}

// GetApikeyOk returns a tuple with the Apikey field value
// and a boolean to check if the value has been set.
func (o *RackspaceCredentials) GetApikeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Apikey, true
}

// SetApikey sets field value
func (o *RackspaceCredentials) SetApikey(v string) {
	o.Apikey = v
}

// GetRegion returns the Region field value
func (o *RackspaceCredentials) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *RackspaceCredentials) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *RackspaceCredentials) SetRegion(v string) {
	o.Region = v
}

func (o RackspaceCredentials) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Provider != nil {
		toSerialize["provider"] = o.Provider
	}
	if true {
		toSerialize["username"] = o.Username
	}
	if true {
		toSerialize["apikey"] = o.Apikey
	}
	if true {
		toSerialize["region"] = o.Region
	}
	return json.Marshal(toSerialize)
}

type NullableRackspaceCredentials struct {
	value *RackspaceCredentials
	isSet bool
}

func (v NullableRackspaceCredentials) Get() *RackspaceCredentials {
	return v.value
}

func (v *NullableRackspaceCredentials) Set(val *RackspaceCredentials) {
	v.value = val
	v.isSet = true
}

func (v NullableRackspaceCredentials) IsSet() bool {
	return v.isSet
}

func (v *NullableRackspaceCredentials) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRackspaceCredentials(val *RackspaceCredentials) *NullableRackspaceCredentials {
	return &NullableRackspaceCredentials{value: val, isSet: true}
}

func (v NullableRackspaceCredentials) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRackspaceCredentials) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


