/*
Mist API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: api@mist.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// AuthInfo struct for AuthInfo
type AuthInfo struct {
	Data *AuthInfoData `json:"data,omitempty"`
	Meta *ResponseMetadata `json:"meta,omitempty"`
}

// NewAuthInfo instantiates a new AuthInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthInfo() *AuthInfo {
	this := AuthInfo{}
	return &this
}

// NewAuthInfoWithDefaults instantiates a new AuthInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthInfoWithDefaults() *AuthInfo {
	this := AuthInfo{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AuthInfo) GetData() AuthInfoData {
	if o == nil || o.Data == nil {
		var ret AuthInfoData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthInfo) GetDataOk() (*AuthInfoData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AuthInfo) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given AuthInfoData and assigns it to the Data field.
func (o *AuthInfo) SetData(v AuthInfoData) {
	o.Data = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *AuthInfo) GetMeta() ResponseMetadata {
	if o == nil || o.Meta == nil {
		var ret ResponseMetadata
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthInfo) GetMetaOk() (*ResponseMetadata, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *AuthInfo) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ResponseMetadata and assigns it to the Meta field.
func (o *AuthInfo) SetMeta(v ResponseMetadata) {
	o.Meta = &v
}

func (o AuthInfo) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableAuthInfo struct {
	value *AuthInfo
	isSet bool
}

func (v NullableAuthInfo) Get() *AuthInfo {
	return v.value
}

func (v *NullableAuthInfo) Set(val *AuthInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthInfo(val *AuthInfo) *NullableAuthInfo {
	return &NullableAuthInfo{value: val, isSet: true}
}

func (v NullableAuthInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


