/*
Mist API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
Contact: api@mist.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package mist_sdk

import (
	"encoding/json"
)

// GetLocationResponse struct for GetLocationResponse
type GetLocationResponse struct {
	Data *Location `json:"data,omitempty"`
	Meta *ResponseMetadata `json:"meta,omitempty"`
}

// NewGetLocationResponse instantiates a new GetLocationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLocationResponse() *GetLocationResponse {
	this := GetLocationResponse{}
	return &this
}

// NewGetLocationResponseWithDefaults instantiates a new GetLocationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLocationResponseWithDefaults() *GetLocationResponse {
	this := GetLocationResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetLocationResponse) GetData() Location {
	if o == nil || o.Data == nil {
		var ret Location
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLocationResponse) GetDataOk() (*Location, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetLocationResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given Location and assigns it to the Data field.
func (o *GetLocationResponse) SetData(v Location) {
	o.Data = &v
}

// GetMeta returns the Meta field value if set, zero value otherwise.
func (o *GetLocationResponse) GetMeta() ResponseMetadata {
	if o == nil || o.Meta == nil {
		var ret ResponseMetadata
		return ret
	}
	return *o.Meta
}

// GetMetaOk returns a tuple with the Meta field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLocationResponse) GetMetaOk() (*ResponseMetadata, bool) {
	if o == nil || o.Meta == nil {
		return nil, false
	}
	return o.Meta, true
}

// HasMeta returns a boolean if a field has been set.
func (o *GetLocationResponse) HasMeta() bool {
	if o != nil && o.Meta != nil {
		return true
	}

	return false
}

// SetMeta gets a reference to the given ResponseMetadata and assigns it to the Meta field.
func (o *GetLocationResponse) SetMeta(v ResponseMetadata) {
	o.Meta = &v
}

func (o GetLocationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Meta != nil {
		toSerialize["meta"] = o.Meta
	}
	return json.Marshal(toSerialize)
}

type NullableGetLocationResponse struct {
	value *GetLocationResponse
	isSet bool
}

func (v NullableGetLocationResponse) Get() *GetLocationResponse {
	return v.value
}

func (v *NullableGetLocationResponse) Set(val *GetLocationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLocationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLocationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLocationResponse(val *GetLocationResponse) *NullableGetLocationResponse {
	return &NullableGetLocationResponse{value: val, isSet: true}
}

func (v NullableGetLocationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLocationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


