openapi: 3.0.3
info:
  contact:
    email: api@mist.io
    name: Mist API Team
  title: Mist API
  version: 2.0.0
  x-cli-name: Mist CLI
servers:
- description: Mist Hosted Service
  url: https://mist.io/
paths:
  /api/v2/clouds:
    get:
      description: List clouds owned by the active org. READ permission required on
        cloud.
      operationId: list-clouds
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: List clouds
      tags:
      - clouds
      x-cli-table-default:
      - name
      - provider
      - tags
      x-cli-table-extended:
      - id
      - name
      - provider
      - tags
      - owned_by
      - created_by
    post:
      description: Adds a new cloud and returns the cloud's id. ADD permission required
        on cloud.
      operationId: add-cloud
      security:
      - ApiKeyAuth:
        - add:cloud
      - CookieAuth:
        - add:cloud
      summary: Add cloud
      tags:
      - clouds
  /api/v2/clouds/{cloud}:
    delete:
      description: Remove target cloud
      operationId: remove-cloud
      security:
      - ApiKeyAuth:
        - remove:cloud
      - CookieAuth:
        - remove:cloud
      summary: Remove cloud
      tags:
      - clouds
    get:
      description: Get details about target cloud
      operationId: get-cloud
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: Get cloud
      tags:
      - clouds
      x-cli-table-default:
      - name
      - provider
      - tags
      x-cli-table-extended:
      - id
      - name
      - provider
      - tags
      - owned_by
      - created_by
  /api/v2/clusters:
    get:
      description: List clusters
      operationId: list-clusters
      security:
      - ApiKeyAuth:
        - read:cluster
        - read:cloud
      - CookieAuth:
        - read:cluster
        - read:cloud
      summary: List clusters
      tags:
      - clusters
      x-cli-table-default:
      - name
      - cloud
      - total_nodes
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - total_nodes
      - total_cpus
      - total_ram
      - tags
      - owned_by
      - created_by
    post:
      description: Create a new cluster and return the cluster's id
      operationId: create-cluster
      security:
      - ApiKeyAuth:
        - create:cluster
        - read:cloud
        - create_resources:cloud
      - CookieAuth:
        - create:cluster
        - read:cloud
        - create_resources:cloud
      summary: Create cluster
      tags:
      - clusters
  /api/v2/clusters/{cluster}:
    delete:
      description: Destroy target clusters
      operationId: destroy-cluster
      security:
      - ApiKeyAuth:
        - read:cloud
        - destroy:cluster
      - CookieAuth:
        - read:cloud
        - destroy:cluster
      summary: Destroy cluster
      tags:
      - clusters
    get:
      description: Get details about target cluster
      operationId: get-cluster
      security:
      - ApiKeyAuth:
        - read:cluster
        - read:cloud
      - CookieAuth:
        - read:cluster
        - read:cloud
      summary: Get cluster
      tags:
      - clusters
      x-cli-table-default:
      - name
      - cloud
      - total_nodes
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - total_nodes
      - total_cpus
      - total_ram
      - tags
      - owned_by
      - created_by
  /api/v2/datapoints:
    get:
      description: Get datapoints for a specific query
      operationId: get-datapoints
      security:
      - ApiKeyAuth:
        - read:cloud
        - read:machine
      - CookieAuth:
        - read:cloud
        - read:machine
      summary: Get datapoints
      tags:
      - datapoints
  /api/v2/images:
    get:
      description: List images owned by the active org. READ permission required on
        image & cloud.
      operationId: list-images
      security:
      - ApiKeyAuth:
        - read:image
        - read:cloud
      - CookieAuth:
        - read:image
        - read:cloud
      summary: List images
      tags:
      - images
      x-cli-table-default:
      - starred
      - name
      - cloud
      - os_type
      - tags
      x-cli-table-extended:
      - starred
      - id
      - external_id
      - name
      - cloud
      - os_type
      - tags
      - owned_by
      - created_by
  /api/v2/images/{image}:
    get:
      description: Get details about target image
      operationId: get-image
      security:
      - ApiKeyAuth:
        - read:image
        - read:cloud
      - CookieAuth:
        - read:image
        - read:cloud
      summary: Get image
      tags:
      - images
      x-cli-table-default:
      - starred
      - name
      - cloud
      - os_type
      - tags
      x-cli-table-extended:
      - starred
      - id
      - external_id
      - name
      - cloud
      - os_type
      - tags
      - owned_by
      - created_by
  /api/v2/jobs/{job_id}:
    get:
      description: "null"
      operationId: get-job
      security:
      - ApiKeyAuth:
        - read:job
      - CookieAuth:
        - read:job
      summary: Get job
      tags:
      - jobs
  /api/v2/keys:
    get:
      description: List keys owned by the active org. READ permission required on
        key.
      operationId: list-keys
      security:
      - ApiKeyAuth:
        - read:key
      - CookieAuth:
        - read:key
      summary: List keys
      tags:
      - keys
      x-cli-table-default:
      - name
      - default
      - tags
      x-cli-table-extended:
      - id
      - name
      - default
      - tags
      - owned_by
      - created_by
    post:
      description: Adds a new key and returns the key's id. ADD permission required
        on key.
      operationId: add-key
      security:
      - ApiKeyAuth:
        - add:key
      - CookieAuth:
        - add:key
      summary: Add key
      tags:
      - keys
  /api/v2/keys/{key}:
    delete:
      description: Delete target key
      operationId: delete-key
      security:
      - ApiKeyAuth:
        - delete:key
      - CookieAuth:
        - delete:key
      summary: Delete key
      tags:
      - keys
    get:
      description: Get details about target key
      operationId: get-key
      security:
      - ApiKeyAuth:
        - read:key
      - CookieAuth:
        - read:key
      summary: Get key
      tags:
      - keys
      x-cli-table-default:
      - name
      - default
      - tags
      x-cli-table-extended:
      - id
      - name
      - default
      - tags
      - owned_by
      - created_by
    put:
      description: Edit target key
      operationId: edit-key
      security:
      - ApiKeyAuth:
        - edit:key
      - CookieAuth:
        - edit:key
      summary: Edit key
      tags:
      - keys
  /api/v2/locations:
    get:
      description: List locations owned by the active org. READ permission required
        on location & cloud.
      operationId: list-locations
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: List locations
      tags:
      - locations
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
  /api/v2/locations/{location}:
    get:
      description: Get details about target location
      operationId: get-location
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: Get location
      tags:
      - locations
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - locations
      - external_id
      - machines
  /api/v2/machines:
    get:
      description: List machines owned by the active org. READ permission required
        on machine & cloud.
      operationId: list-machines
      security:
      - ApiKeyAuth:
        - read:machine
        - read:cloud
      - CookieAuth:
        - read:machine
        - read:cloud
      summary: List machines
      tags:
      - machines
      x-cli-table-default:
      - name
      - cloud
      - state
      - tags
      x-cli-table-extended:
      - id
      - name
      - state
      - cloud
      - external_id
      - public_ips
      - tags
      - owned_by
      - created_by
  /api/v2/machines/{machine}:
    get:
      description: Get details about target machine
      operationId: get-machine
      security:
      - ApiKeyAuth:
        - read:machine
        - read:cloud
      - CookieAuth:
        - read:machine
        - read:cloud
      summary: Get machine
      tags:
      - machines
      x-cli-table-default:
      - name
      - cloud
      - state
      - tags
      x-cli-table-extended:
      - id
      - name
      - state
      - cloud
      - external_id
      - public_ips
      - tags
      - owned_by
      - created_by
    put:
      description: Edit target machine
      operationId: edit-machine
      security:
      - ApiKeyAuth:
        - edit:machine
      - CookieAuth:
        - edit:machine
      summary: Edit machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/associate-key:
    put:
      description: Associate a key with a machine.
      operationId: associate-key
      security:
      - ApiKeyAuth:
        - associate_key:machine
        - read:cloud
        - read_private:key
      - CookieAuth:
        - associate_key:machine
        - read:cloud
        - read_private:key
      summary: Associate a key with a machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/clone:
    post:
      description: Clone target machine
      operationId: clone-machine
      security:
      - ApiKeyAuth:
        - clone:machine
      - CookieAuth:
        - clone:machine
      summary: Clone machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/console:
    post:
      description: Open VNC console on target machine
      operationId: console
      security:
      - ApiKeyAuth:
        - console:machine
      - CookieAuth:
        - console:machine
      summary: Open console
      tags:
      - machines
    x-cli-ignore: true
  /api/v2/machines/{machine}/actions/destroy:
    post:
      description: Destroy target machine
      operationId: destroy-machine
      security:
      - ApiKeyAuth:
        - destroy:machine
      - CookieAuth:
        - destroy:machine
      summary: Destroy machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/disassociate-key:
    delete:
      description: Disassociate a key from a machine.
      operationId: disassociate-key
      security:
      - ApiKeyAuth:
        - disassociate_key:machine
        - read:cloud
      - CookieAuth:
        - disassociate_key:machine
        - read:cloud
      summary: Disassociate a key from a machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/reboot:
    post:
      description: Reboot target machine
      operationId: reboot-machine
      security:
      - ApiKeyAuth:
        - reboot:machine
      - CookieAuth:
        - reboot:machine
      summary: Reboot machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/rename:
    post:
      description: Rename target machine
      operationId: rename-machine
      security:
      - ApiKeyAuth:
        - rename:machine
      - CookieAuth:
        - rename:machine
      summary: Rename machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/resize:
    post:
      description: Resize target machine
      operationId: resize-machine
      security:
      - ApiKeyAuth:
        - resize:machine
      - CookieAuth:
        - resize:machine
      summary: Resize machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/resume:
    post:
      description: Resume target machine
      operationId: resume-machine
      security:
      - ApiKeyAuth:
        - resume:machine
      - CookieAuth:
        - resume:machine
      summary: Resume machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/ssh:
    post:
      description: Open secure shell on target machine
      operationId: ssh
      security:
      - ApiKeyAuth:
        - read:cloud
        - read:machine
        - ssh:machine
      - CookieAuth:
        - read:cloud
        - read:machine
        - ssh:machine
      summary: Open secure shell
      tags:
      - machines
    x-cli-ignore: true
  /api/v2/machines/{machine}/actions/start:
    post:
      description: Start target machine
      operationId: start-machine
      security:
      - ApiKeyAuth:
        - start:machine
      - CookieAuth:
        - start:machine
      summary: Start machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/stop:
    post:
      description: Stop target machine
      operationId: stop-machine
      security:
      - ApiKeyAuth:
        - stop:machine
      - CookieAuth:
        - stop:machine
      summary: Stop machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/suspend:
    post:
      description: Suspend target machine
      operationId: suspend-machine
      security:
      - ApiKeyAuth:
        - suspend:machine
      - CookieAuth:
        - suspend:machine
      summary: Suspend machine
      tags:
      - machines
  /api/v2/machines/{machine}/actions/undefine:
    post:
      description: Undefine target machine
      operationId: undefine-machine
      security:
      - ApiKeyAuth:
        - undefine:machine
      - CookieAuth:
        - undefine:machine
      summary: Undefine machine
      tags:
      - machines
  /api/v2/machines/{machine}/snapshots:
    get:
      description: List snapshots of target machine
      operationId: list-snapshots
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
      summary: List machine snapshots
      tags:
      - snapshots
    post:
      description: Create snapshots of target machine
      operationId: create-snapshot
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      summary: Create snapshot
      tags:
      - snapshots
  /api/v2/machines/{machine}/snapshots/{snapshot}:
    delete:
      description: Remove target machine snapshot
      operationId: remove-snapshot
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
        - create_snapshots:machine
      summary: Remove snapshot
      tags:
      - snapshots
    post:
      description: Revert machine to snapshot
      operationId: revert-to-snapshot
      security:
      - ApiKeyAuth:
        - read:machine
        - list_snapshots:machine
        - revert_to_snapshots:machine
      - CookieAuth:
        - read:machine
        - list_snapshots:machine
        - revert_to_snapshots:machine
      summary: Revert to snapshot
      tags:
      - snapshots
  /api/v2/networks:
    get:
      description: List networks owned by the active org. READ permission required
        on network & cloud.
      operationId: list-networks
      security:
      - ApiKeyAuth:
        - read:network
        - read:cloud
      - CookieAuth:
        - read:network
        - read:cloud
      summary: List networks
      tags:
      - networks
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
      - tags
      - owned_by
      - created_by
    post:
      description: Creates one or more networks on the specified cloud. If async is
        true, a jobId will be returned. READ permission required on cloud. CREATE_RESOURCES
        permission required on cloud. CREATE permission required on network.
      operationId: create-network
      security:
      - ApiKeyAuth:
        - create:network
        - read:cloud
        - create_resources:cloud
      - CookieAuth:
        - create:network
        - read:cloud
        - create_resources:cloud
      summary: Create network
      tags:
      - networks
  /api/v2/networks/{network}:
    delete:
      description: Delete target network
      operationId: delete-network
      security:
      - ApiKeyAuth:
        - read:cloud
        - read:network
        - remove:network
      - CookieAuth:
        - read:cloud
        - read:network
        - remove:network
      summary: Delete network
      tags:
      - networks
    get:
      description: Get details about target network
      operationId: get-network
      security:
      - ApiKeyAuth:
        - read:network
        - read:cloud
      - CookieAuth:
        - read:network
        - read:cloud
      summary: Get network
      tags:
      - networks
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - location
      - external_id
      - subnets
      - machines
      - tags
      - owned_by
      - created_by
    put:
      description: Edit target network
      operationId: edit-network
      security:
      - ApiKeyAuth:
        - edit:network
      - CookieAuth:
        - edit:network
      summary: Edit network
      tags:
      - networks
  /api/v2/orgs:
    get:
      description: List orgs owned by the requester. If parameter allorgs is true
        and requester is an admin then all orgs will be listed.
      operationId: list-orgs
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: List orgs
      tags:
      - orgs
      x-cli-table-default:
      - name
      - clouds_count
      - teams_count
      x-cli-table-extended:
      - name
      - id
      - clouds_count
      - teams_count
      - last_active
    x-cli-ignore: true
  /api/v2/orgs/{org}:
    get:
      description: Get details about target org
      operationId: get-org
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: Get Org
      tags:
      - orgs
      x-cli-table-extended:
      - name
      - id
      - clouds_count
      - total_machine_count
      - last_active
    x-cli-ignore: true
  /api/v2/orgs/{org}/members:
    get:
      description: List org members owned by the requester. The requester must be
        a member of the org.
      operationId: list-org-members
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: List org members
      tags:
      - orgs
      x-cli-table-default:
      - email
      x-cli-table-extended:
      - email
      - id
      - last_login
      - registration_date
    x-cli-ignore: true
  /api/v2/orgs/{org}/members/{member}:
    get:
      description: Get details about target member
      operationId: get-member
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: Get Org
      tags:
      - orgs
      x-cli-table-default:
      - email
      x-cli-table-extended:
      - email
      - id
      - last_login
      - registration_date
    x-cli-ignore: true
  /api/v2/orgs/{org}/teams:
    get:
      description: List teams in org.
      operationId: list-org-teams
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: List org teams
      tags:
      - orgs
      x-cli-table-default:
      - name
      - members_count
      x-cli-table-extended:
      - id
      - name
      - members_count
      - members
      - description
      - policy
    x-cli-ignore: true
  /api/v2/rules:
    get:
      description: Return a filtered list of rules
      operationId: list-rules
      security:
      - ApiKeyAuth:
        - read:rule
      - CookieAuth:
        - read:rule
      summary: List rules
      tags:
      - rules
      x-cli-table-default:
      - name
      - queries
      - actions
      - tags
      x-cli-table-extended:
      - id
      - name
      - resource_type
      - selectors
      - queries
      - actions
      - window
      - frequency
      - tags
    post:
      description: Add a new rule, READ permission required on target resource, ADD
        permission required on Rule
      operationId: add-rule
      security:
      - ApiKeyAuth:
        - add:rule
      - CookieAuth:
        - add:rule
      summary: Add rule
      tags:
      - rules
  /api/v2/rules/{rule}:
    delete:
      description: Delete a rule given its UUID.
      operationId: delete-rule
      security:
      - ApiKeyAuth:
        - delete:rule
      - CookieAuth:
        - delete:rule
      summary: Delete rule
      tags:
      - rules
    get:
      description: Get details about target rule
      operationId: get-rule
      security:
      - ApiKeyAuth:
        - read:rule
      - CookieAuth:
        - read:rule
      summary: Get rule
      tags:
      - rules
      x-cli-table-default:
      - name
      - queries
      - actions
      - tags
      x-cli-table-extended:
      - id
      - name
      - resource_type
      - selectors
      - queries
      - actions
      - window
      - frequency
      - tags
    patch:
      description: Rename a rule
      operationId: rename-rule
      security:
      - ApiKeyAuth:
        - write:rule
      - CookieAuth:
        - write:rule
      summary: Rename rule
      tags:
      - rules
    post:
      description: Edit a rule given its UUID, EDIT permission required on rule
      operationId: edit-rule
      security:
      - ApiKeyAuth:
        - read:cloud
        - edit:rule
      - CookieAuth:
        - read:cloud
        - edit:rule
      summary: Update rule
      tags:
      - rules
    put:
      description: Enable or disable a rule
      operationId: toggle-rule
      security:
      - ApiKeyAuth:
        - write:rule
      - CookieAuth:
        - write:rule
      summary: Toggle rule
      tags:
      - rules
  /api/v2/scripts:
    get:
      description: List scripts owned by the active org. READ permission required
        on script.
      operationId: list-scripts
      security:
      - ApiKeyAuth:
        - read:script
      - CookieAuth:
        - read:script
      summary: List scripts
      tags:
      - scripts
      x-cli-table-default:
      - name
      - tags
      x-cli-table-extended:
      - id
      - name
      - description
      - tags
      - owned_by
      - created_by
    post:
      description: Add script to user scripts
      operationId: add-script
      security:
      - ApiKeyAuth:
        - add:script
      - CookieAuth:
        - add:script
      summary: Add script
      tags:
      - scripts
  /api/v2/scripts/{script}:
    delete:
      description: Delete target script
      operationId: delete-script
      security:
      - ApiKeyAuth:
        - delete:script
      - CookieAuth:
        - delete:script
      summary: Delete script
      tags:
      - scripts
    get:
      description: Get details about target script
      operationId: get-script
      security:
      - ApiKeyAuth:
        - read:script
      - CookieAuth:
        - read:script
      summary: Get script
      tags:
      - scripts
      x-cli-table-default:
      - name
      - tags
      x-cli-table-extended:
      - id
      - name
      - description
      - tags
      - owned_by
      - created_by
    post:
      description: Start a script job to run the script.
      operationId: run-script
      security:
      - ApiKeyAuth:
        - read:cloud
        - run_script:machine
        - run:script
      - CookieAuth:
        - read:cloud
        - run_script:machine
        - run:script
      summary: Run script
      tags:
      - scripts
    put:
      description: Edit target script
      operationId: edit-script
      security:
      - ApiKeyAuth:
        - edit:script
      - CookieAuth:
        - edit:script
      summary: Edit script
      tags:
      - scripts
  /api/v2/scripts/{script}/file:
    get:
      description: Download script file or archive
      operationId: download-script
      summary: Download script
      tags:
      - scripts
  /api/v2/scripts/{script}/url:
    get:
      description: Generate url for fetching script file
      operationId: generate-script-url
      security:
      - ApiKeyAuth:
        - read:script
      - CookieAuth:
        - read:script
      summary: Generate script url
      tags:
      - scripts
  /api/v2/sizes:
    get:
      description: List sizes owned by the active org. READ permission required on
        size & cloud.
      operationId: list-sizes
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: List sizes
      tags:
      - sizes
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
  /api/v2/sizes/{size}:
    get:
      description: Get details about target size
      operationId: get-size
      security:
      - ApiKeyAuth:
        - read:cloud
      - CookieAuth:
        - read:cloud
      summary: Get size
      tags:
      - sizes
      x-cli-table-default:
      - name
      - cloud
      x-cli-table-extended:
      - id
      - name
      - cloud
      - locations
      - external_id
      - machines
  /api/v2/users:
    get:
      description: Return current user if requester is not admin. Return all users
        for admin.
      operationId: list-users
      security:
      - ApiKeyAuth:
        - ""
      - CookieAuth:
        - ""
      summary: List users
      tags:
      - users
      x-cli-table-default:
      - email
      x-cli-table-extended:
      - email
      - id
      - last_login
      - registration_date
  /api/v2/volumes:
    get:
      description: List volumes owned by the active org. READ permission required
        on volume & cloud.
      operationId: list-volumes
      security:
      - ApiKeyAuth:
        - read:volume
        - read:cloud
      - CookieAuth:
        - read:volume
        - read:cloud
      summary: List volumes
      tags:
      - volumes
      x-cli-table-default:
      - name
      - size
      - cloud
      - location
      - attached_to
      - tags
      x-cli-table-extended:
      - id
      - name
      - size
      - cloud
      - location
      - external_id
      - attached_to
      - tags
      - owned_by
      - created_by
    post:
      description: Creates one or more volumes on the specified cloud. If async is
        true, a jobId will be returned. READ permission required on cloud. CREATE_RESOURCES
        permission required on cloud. READ permission required on location. CREATE_RESOURCES
        permission required on location. CREATE permission required on volume.
      operationId: create-volume
      security:
      - ApiKeyAuth:
        - create:volume
        - read:cloud
        - create_resources:cloud
        - read:location
        - create_resources:location
      - CookieAuth:
        - create:volume
        - read:cloud
        - create_resources:cloud
        - read:location
        - create_resources:location
      summary: Create volume
      tags:
      - volumes
  /api/v2/volumes/{volume}:
    delete:
      description: Delete target volume
      operationId: delete-volume
      security:
      - ApiKeyAuth:
        - read:volume
        - delete:volume
        - read:cloud
      - CookieAuth:
        - read:volume
        - delete:volume
        - read:cloud
      summary: Delete volume
      tags:
      - volumes
    get:
      description: Get details about target volume
      operationId: get-volume
      security:
      - ApiKeyAuth:
        - read:volume
        - read:cloud
      - CookieAuth:
        - read:volume
        - read:cloud
      summary: Get volume
      tags:
      - volumes
      x-cli-table-default:
      - name
      - size
      - cloud
      - location
      - attached_to
      - tags
      x-cli-table-extended:
      - id
      - name
      - size
      - cloud
      - location
      - external_id
      - attached_to
      - tags
      - owned_by
      - created_by
    put:
      description: Edit target volume
      operationId: edit-volume
      security:
      - ApiKeyAuth:
        - edit:volume
        - read:cloud
      - CookieAuth:
        - edit:volume
        - read:cloud
      summary: Edit volume
      tags:
      - volumes
  /api/v2/zones:
    get:
      description: List zones owned by the active org. READ permission required on
        zone & cloud.
      operationId: list-zones
      security:
      - ApiKeyAuth:
        - read:zone
        - read:cloud
      - CookieAuth:
        - read:zone
        - read:cloud
      summary: List zones
      tags:
      - zones
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - external_id
      - machines
      - tags
      - owned_by
      - created_by
    post:
      description: Creates one or more zones on the specified cloud. If async is true,
        a jobId will be returned. READ permission required on cloud. CREATE_RESOURCES
        permission required on cloud. CREATE permission required on zone.
      operationId: create-zone
      security:
      - ApiKeyAuth:
        - create:zone
        - read:cloud
        - create_resources:cloud
      - CookieAuth:
        - create:zone
        - read:cloud
        - create_resources:cloud
      summary: Create zone
      tags:
      - zones
  /api/v2/zones/{zone}:
    delete:
      description: Delete target zone
      operationId: delete-zone
      security:
      - ApiKeyAuth:
        - read:zone
        - delete:zone
        - read:cloud
      - CookieAuth:
        - read:zone
        - delete:zone
        - read:cloud
      summary: Delete zone
      tags:
      - zones
    get:
      description: Get details about target zone
      operationId: get-zone
      security:
      - ApiKeyAuth:
        - read:zone
        - read:cloud
      - CookieAuth:
        - read:zone
        - read:cloud
      summary: Get zone
      tags:
      - zones
      x-cli-table-default:
      - name
      - cloud
      - machines
      - tags
      x-cli-table-extended:
      - id
      - name
      - cloud
      - location
      - external_id
      - subnets
      - machines
      - tags
      - owned_by
      - created_by
    put:
      description: Edit target zone
      operationId: edit-zone
      security:
      - ApiKeyAuth:
        - edit:zone
      - CookieAuth:
        - edit:zone
      summary: Edit zone
      tags:
      - zones
components:
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: Authorization
      type: apiKey
    CookieAuth:
      in: cookie
      name: session.id
      type: apiKey
